In [1]:
# Load library
import numpy as np

In [2]:
# Create matrix
matrix = np.array([
[1, 2, 3],
[2, 4, 6],
[3, 8, 9]])

In [3]:
# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

In [4]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [5]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([2, 8])